version: '3.8'

services:
  web:
    image: karaoke-maker-prod:0.1
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    env_file:
      - ./.env
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
      